### ISSUE TITLE
TargetPlatform.windows is not yet supported by the plugin

### ISSUE THREAD

**Issue by awinkwinky** [ssk-flutter/functional_admob_flutter#3]
i have tried to run app in windows desktop 

in plugin header have supported in windows.

but app show text:
"TargetPlatform.windows is not yet supported by the plugin"

is there any something to setup again in app code...
especially in folder windows ?

thanks...

**Comment by deviankim** [comment]
Actually this library depends on https://pub.dev/packages/admob_flutter.
So, windows platform is not supported.
And I could find how to show appropriate supporting platforms.
Sorry @awinkwinky

**Comment by awinkwinky** [comment]
ok.. i understand...
thank you very much for your information...

**Comment by TheSeriousProgrammer** [comment]
I too came here hoping for desktop/web support , can you remove those platforms in the project's support list. Thanks for your work!
